# Generated by Django 2.1.4 on 2019-01-21 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('owner_id', models.CharField(default='', max_length=16, verbose_name='用户id')),
                ('image', models.ImageField(max_length=255, upload_to='bankcards')),
                ('card_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='卡号码')),
                ('bank', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属银行')),
                ('card_type', models.IntegerField(blank=True, null=True, verbose_name='类型')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('owner_id', models.CharField(default='', max_length=16, verbose_name='用户id')),
                ('image', models.ImageField(max_length=255, upload_to='idcards')),
                ('id_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='身份证号码')),
                ('id_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=8, null=True, verbose_name='性别')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='地址')),
                ('nation', models.CharField(blank=True, max_length=8, null=True, verbose_name='民族')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
        ),
    ]
